name: Typescript CI

on:
    push:
        branches: [ lab1, lab3, lab4 ]
    pull_request: 
        branches: [ lab1, lab3, lab4 ]

jobs:
    build:
        name: Build and Test
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install dependencies
              run: |
                npm ci

            - name: Run tests
              run: |
                npm test
